{% set name = "amdnet" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amdnet-{{ version }}.tar.gz
  sha256: c425362e74483b0c77f7e61ae26db9898c0ae4913f29522937c44283e6ebc4ba

build:
  number: 0
  noarch: python
  entry_points:
    - amdnet = train_AMDNet:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.6,<3.9
  run:
    - keras ==2.7.0
    - matminer ==0.7.4
    - matplotlib-base ==3.5.1
    - networkx ==2.6.3
    - pandas
    - pybel
    - pymatgen ==2022.1.9
    - python >=3.6,<3.9
    - robocrys ==0.2.7
    - scipy
    - tensorflow
    - tqdm

test:
  imports:
    - amdnet
    - amdnet.layers
  commands:
    - pip check
    - amdnet --help
  requires:
    - pip

about:
  home: https://pypi.org/project/amdnet/
  summary: Structure motif-centric learning framework for inorganic crystalline systems.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
